[package]
name = "librespot-metadata"
version = "0.1.0"
authors = ["Paul Lietar <paul@lietar.net>"]

[dependencies]
byteorder = "1.3.2"
futures = "0.1.28"
linear-map = "1.2.0"
protobuf = "~2.8.1"

[dependencies.librespot-core]
path = "../core"
[dependencies.librespot-protocol]
path = "../protocol"
