[package]
name = "librespot-audio"
version = "0.1.0"
authors = ["Paul Lietar <paul@lietar.net>"]

[dependencies]
bit-set = "0.4.0"
byteorder = "1.2.1"
futures = "0.1.23"
lewton = "0.8.0"
log = "0.4.0"
num-bigint = "0.1.35"
num-traits = "0.1.36"
tempfile = "2.1"
aes-ctr = "0.3.0"

tremor = { git = "https://github.com/plietar/rust-tremor", optional = true }
vorbis = { version ="0.1.0", optional = true }

[dependencies.librespot-core]
path = "../core"

[features]
with-tremor = ["tremor"]
with-vorbis = ["vorbis"]
